"""Update jobs model for detailed experience information

Revision ID: b40f8785c5cb
Revises: 2a41073f7e03
Create Date: 2025-12-06 15:03:27.794516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b40f8785c5cb'
down_revision: Union[str, Sequence[str], None] = '2a41073f7e03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('employment_type', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('min_experience_years', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('max_experience_years', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('experience_level', sa.String(), nullable=True))
    op.drop_column('jobs', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('jobs', 'experience_level')
    op.drop_column('jobs', 'max_experience_years')
    op.drop_column('jobs', 'min_experience_years')
    op.drop_column('jobs', 'employment_type')
    # ### end Alembic commands ###
